name: build_resolvers
version: 1.5.1
description: Resolve Dart code in a Builder
homepage: https://github.com/dart-lang/build/tree/master/build_resolvers

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  analyzer: ">=0.40.1 <0.42.0"
  build:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build
  crypto: ^2.0.0
  graphs: ^0.2.0
  logging: ^0.11.2
  meta: ^1.2.3
  path: ^1.1.0
  package_config: ^1.9.3
  pool: ^1.4.0
  pub_semver: ^1.3.0

dev_dependencies:
  test: ^1.0.0
  build_test:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build

dependency_overrides:
  build:
    path: ../build
