name: build_web_compilers
version: 2.16.0
description: Builder implementations wrapping Dart compilers.
homepage: https://github.com/dart-lang/build/tree/master/build_web_compilers

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  analyzer: ">=0.36.4 <0.42.0"
  archive: ^2.0.0
  bazel_worker: ^0.1.18
  build:
    path: '../build'
  build_config:
    path: '../build_config'
  build_modules:
    path: '../build_modules'
  collection: ^1.0.0
  glob: ^1.1.0
  js: ^0.6.1
  logging: ^0.11.2
  meta: ^1.1.0
  path: ^1.4.2
  pool: ^1.3.0
  scratch_space:
    path: '../scratch_space'
  source_maps: ^0.10.4
  source_span: ^1.4.0
  stack_trace: ^1.9.2

dev_dependencies:
  build_runner:
    path: '../build_runner'
  build_test:
    path: '../build_test'
  test: ^1.0.0
  a:
    path: test/fixtures/a
  b:
    path: test/fixtures/b
