name: build_web_compilers
version: 2.16.0
description: Builder implementations wrapping Dart compilers.
homepage: https://github.com/dart-lang/build/tree/master/build_web_compilers

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  analyzer: ">=0.36.4 <0.42.0"
  archive: ^2.0.0
  bazel_worker: ^0.1.18
  build:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build
  build_config:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build_config
  build_modules:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build_modules
  collection: ^1.0.0
  glob: ^1.1.0
  js: ^0.6.1
  logging: ^0.11.2
  meta: ^1.1.0
  path: ^1.4.2
  pool: ^1.3.0
  scratch_space:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: scratch_space
  source_maps: ^0.10.4
  source_span: ^1.4.0
  stack_trace: ^1.9.2

dev_dependencies:
  build_runner:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build_runner
  build_test:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build_test
  test: ^1.0.0
  a:
    path: test/fixtures/a
  b:
    path: test/fixtures/b
