name: build_modules
version: 3.0.2
description: Builders for Dart modules
repository: https://github.com/dart-lang/build/tree/master/build_modules

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  analyzer: ">0.36.4 <0.42.0"
  async: ^2.0.0
  bazel_worker: ^0.1.20
  build:
    path: '../build'
  build_config:
    path: '../build_config'
  collection: ^1.0.0
  crypto: ^2.0.0
  glob: ^1.0.0
  graphs: ^0.2.0
  json_annotation: ">=1.2.0 <5.0.0"
  logging: ^0.11.2
  meta: ^1.1.0
  path: ^1.4.2
  pedantic: ^1.0.0
  scratch_space:
    path: '../scratch_space'

dev_dependencies:
  # Used inside tests
  build_runner:
    path: '../build_runner'
  build_test:
    path: '../build_test'
  test: ^1.6.0
  a:
    path: test/fixtures/a
  b:
    path: test/fixtures/b
