name: _test_null_safety
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  js: ^0.6.3-nullsafety
  test: ^1.16.0-nullsafety

dependency_overrides:
  build:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build
  build_config:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build_config
  build_daemon:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build_daemon
  build_modules:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build_modules
  build_resolvers:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build_resolvers
  build_runner:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build_runner
  build_runner_core:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build_runner_core
  build_test:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build_test
  build_vm_compilers:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build_vm_compilers
  build_web_compilers:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build_web_compilers
  scratch_space:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: scratch_space
