name: build_test
description: Utilities for writing unit tests of Builders.
version: 1.3.2
homepage: https://github.com/dart-lang/build/tree/master/build_test

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  async: ">=1.2.0 <3.0.0"
  build:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build
  build_config:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build_config
  build_resolvers:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build_resolvers
  crypto: ">=0.9.2 <3.0.0"
  glob: ^1.1.0
  html: ">=0.9.0 <0.15.0"
  logging: ^0.11.2
  matcher: ^0.12.0
  package_config: ^1.9.0
  path: ^1.4.1
  pedantic: ^1.0.0
  stream_transform: ">=0.0.20 <2.0.0"
  test: '>=0.12.42 <2.0.0'
  test_core: '>=0.3.6 <0.4.0'
  watcher: ^0.9.7

dev_dependencies:
  analyzer: ">=0.35.4 <0.42.0"
  collection: ^1.14.0
