name: scratch_space
version: 0.0.4+3-dev
description: A tool to manage running external executables within package:build
homepage: https://github.com/dart-lang/build/tree/master/scratch_space

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  build:
    path: '../build'
  crypto: ">=2.0.3 <3.0.0"
  path: ^1.1.0
  pedantic: ^1.0.0
  pool: ^1.0.0

dev_dependencies:
  build_runner:
    path: '../build_runner'
  build_test:
    path: '../build_test'
  test: ^1.0.0
