name: _test
publish_to: none

environment:
  sdk: ">=2.3.0 <3.0.0"

dev_dependencies:
  analyzer: ^0.41.0
  path: ^1.4.2
  test: ^1.6.2
  test_process: ^1.0.4
  provides_builder:
    path: pkgs/provides_builder/

dependency_overrides:
  build:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build
  build_config:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build_config
  build_daemon:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build_daemon
  build_modules:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build_modules
  build_resolvers:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build_resolvers
  build_runner:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build_runner
  build_runner_core:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build_runner_core
  build_test:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build_test
  build_vm_compilers:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build_vm_compilers
  build_web_compilers:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: build_web_compilers
  scratch_space:
    git:
      url: https://github.com/vrnvorona/build
      ref: cache_and_build_folder_fix
      path: scratch_space
